config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"

  # [Passing from Old WordPress URLs]
  get "archives/:book_slug/:id" => "wordpress_passers#show", as: :wordpress_passer

  # [User Auths (Default)]
  resource :session, except: [:show]
  resources :passwords, param: :token

  # [User Features]
  resources :users, only: [:new, :create, :show]

  # [Book Features]
  resources :books, param: :slug do
    get ':year', to: 'books#show', on: :member, as: :show_with_year, constraints: { year: /\d{4}/ }
    get ':year/:month', to: 'books#show', on: :member, as: :show_with_year_and_month, constraints: { year: /\d{4}/, month: /\d{1,2}/ }

    get 'rss', to: 'books#rss', on: :member

    resources :random_articles, only: [:index]
  end

  # [Article Features]
  resources :articles

  # [Random Article Feature]
  resources :random_articles, only: [:index]

  # [API Features]
  namespace :api do
    namespace :v1 do
      resources :articles, only: [:index, :show]
    end
  end
end

app/models/random_article.rb
class RandomArticle
  include ActiveModel::Model

  attr_reader :article, :book

  def initialize(book: nil)
    @book = book
  end

  def article
    @article ||= fetch_random_article
  end

  private

  def fetch_random_article
    if @book.present?
      book.articles.published.sample
    else
      Article.published.sample
    end
  end
end

app/controllers/random_articles_controller.rb
class RandomArticlesController < ApplicationController
  allow_unauthenticated_access only: [:index]

  def index
    @book = Book.find_by(slug: params[:book_slug])
    @random_article = RandomArticle.new(book: @book)
    @article = @random_article.article
  end
end

app/views/random_articles/index.html.erb
<div id="diain-logo">
  <%= link_to books_path do %>
    produced by
    <span class="diarin-name">Diarin</span>
  <% end %>
</div>
<div id="book-title-wrapper">
  <%= link_to book_path(@article.book) do %>
    <div id="book-title">
      <h1><%= @article.book.title %></h1>
      <h2><%= @article.book.description %></h2>
    </div>
  <% end %>
</div>

<%= tag.div class: "article article--#{@article.book.theme_slug}" do %>
  <div class="article__content">
    <div class="article__content__title">
      <h1><%= @article.title %></h1>
      <div class="article__content__title__date">
        <%= date_only(@article.published_at) || @article.status %>
      </div>
    </div>
    <div class="article__content__body">
      <%= body_with_pre_wrap(@article) %>
    </div>
  </div>
  <p class="article__meta">
    <%= date_only(@article.published_at) || @article.status %>
    <% if author?(@article) %>
      <span>（<%= artcile_char_counts(@article) %>文字）</span>
    <% end %>
    <%= debug_id(@article) %>
  </p>
  <div class="article__action-buttons">
    <div>
      <% if @book.present? %>
        <%= link_to "さらに読む", book_random_articles_path(@book) %>
      <% else %>
      <%= link_to "さらに読む", random_articles_path %>
      <% end %>
    </div>
  </div>
  <% if author?(@article) %>
    <div class="article__action-buttons">
      <div>
        <%= link_to "編集", edit_article_path(@article) %>
      </div>
      <div>
        <% if @article.status != 'deleted' %>
          <%= link_to "削除", article_path(@article), data: {turbo_method: :delete, turbo_confirm: "後悔しませんね？"} %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>