config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"

  # [Passing from Old WordPress URLs]
  get "archives/:book_slug/:id" => "wordpress_passers#show", as: :wordpress_passer

  # [User Auths (Default)]
  resource :session, except: [:show]
  resources :passwords, param: :token

  # [User Features]
  resources :users, only: [:new, :create, :show]

  # [Book Features]
  resources :books, param: :slug do
    get ':year', to: 'books#show', on: :member, as: :show_with_year, constraints: { year: /\d{4}/ }
    get ':year/:month', to: 'books#show', on: :member, as: :show_with_year_and_month, constraints: { year: /\d{4}/, month: /\d{1,2}/ }

    get 'rss', to: 'books#rss', on: :member

    resources :random_articles, only: [:index]
  end

  # [Article Features]
  resources :articles

  # [Random Article Feature]
  resources :random_articles, only: [:index]

  # [API Features]
  namespace :api do
    namespace :v1 do
      resources :articles, only: [:index, :show]
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  OFFICIAL_STATUSES = %w[draft publish private deleted]

  belongs_to :book

  scope :published, -> { where(status: :publish).where('published_at < ?', Time.zone.now) }

  scope :with_year, -> (year) {
    start_date = Time.zone.local(year.to_i, 1, 1).beginning_of_year
    end_date = start_date.end_of_year
    where(published_at: start_date..end_date)
  }

  scope :with_year_month, -> (year, month) {
    start_date = Time.zone.local(year.to_i, month.to_i, 1).beginning_of_month
    end_date = start_date.end_of_month
    where(published_at: start_date..end_date)
  }

  scope :search, -> (key) {
    where('title LIKE ? OR body LIKE ?', "%#{key}%", "%#{key}%")
  }

  def as_json(options = {})
    super(options.merge(
      except: [:created_at, :updated_at, :imported_id, book_id],
      methods: [:book_slug]
    ))
  end

  def book_slug
    book&.slug || ''
  end

  def prev_article
    @prev_article ||= book.articles.published.where('published_at < ?', published_at).order(published_at: :desc).first
  end

  def next_article
    @next_article ||= book.articles.published.where('published_at > ?', published_at).order(published_at: :asc).first
  end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ActionController::API

  DEFAULT_LIMIT = 20
  MAX_LIMIT = 100

  def index
    @articles = filtered_articles.includes(:book).order(published_at: :desc).limit(limit)
    render json: @articles
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'Not Found' }, status: :not_found
  end

  def show
    @article = Article.find(params[:id])
    render json: @article
  end

  private

  def filtered_articles
    if params[:book_slug].present?
      book = Book.find_by(slug: params[:book_slug])
      return book.articles.published if book.present?
    end

    if params[:author].present?
      user = User.find_by!(email_address: params[:author])
      books = user.books.published
      return Article.where(book: books).published if books.present?
    end

    Article.published
  end

  def limit
    _limit = params[:limit].to_i
    _limit.between?(1, MAX_LIMIT) ? limit : MAX_LIMIT
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  allow_unauthenticated_access only: [:index, :show]

  def index
  end

  def show
    @article = Article.find(params[:id])
    redirect_to books_path if @article.nil?

    @book = @article.book
  end

  def new
    book = Book.find_by(slug: params[:book_slug])
    redirect_to root_path if book.nil?
    @article = book.articles.build
    @books = Current.user.books
  end

  def create
    article = Article.new(article_params)
    if article.save
      redirect_to article_path(article)
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
    redirect_to root_path if @article.nil?

    @books = Current.user.books
  end

  def update
    article = Article.find(params[:id])
    redirect_to root_path if article.nil?

    if article.update(article_params)
      redirect_to article_path(article)
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    redirect_to root_path if article.nil?

    book = article.book
    article.update(status: :deleted)

    redirect_to book_path(book)
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :published_at, :book_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def artcile_char_counts(article)
    strip_tags(article.body).length
  end

  def body_with_pre_wrap(article)
    safe_html = sanitize(body_with_embedding(article), tags: %w(blockquote img a script iframe br), attributes: %w(class href src charset async data-instgrm-permalink))
    safe_html.strip!

    content_tag :span, safe_html.html_safe, style: 'white-space: pre-wrap;'
  end

  def body_with_embedding(article)
    body_html = article.body
    body_html = removing_wordpress_tags(body_html)

    twitter_urls = body_html.scan(/(?<=^|\s)https:\/\/twitter.com\/\w+\/status\/\d+/)
    body_html = twitter_urls.inject(body_html) do |html, url|
      html.gsub(url, twitter_embed(url))
    end

    instagram_urls = body_html.scan(/(?<=^|\s)https:\/\/www.instagram.com\/p\/.+/)
    body_html = instagram_urls.inject(body_html) do |html, url|
      html.gsub(url, instagram_embed(url))
    end

    instagram_reel_urls = body_html.scan(/(?<=^|\s)https:\/\/www.instagram.com\/reel\/.+/)
    body_html = instagram_reel_urls.inject(body_html) do |html, url|
      html.gsub(url, instagram_reel_embed(url))
    end

    youtube_urls = body_html.scan(/(?<=^|\s)https:\/\/www.youtube.com\/watch\?v=[\w-]+/)
    youtube_urls += body_html.scan(/(?<=^|\s)https:\/\/youtu.be\/[\w-]+/)
    youtube_urls += body_html.scan(/(?<=^|\s)https:\/\/www.youtube.com\/live\/.+$/)
    body_html = youtube_urls.inject(body_html) do |html, url|
      html.gsub(url, youtube_embed(url))
    end
  end

  def youtube_embed(url)
    if url.include?('youtu.be')
      video_id = url.split('/').last
    elsif url.include?('live')
      video_id = url.split('/').last
    else
      video_id = url.split('v=').last
    end
    embed_url = "https://www.youtube.com/embed/#{video_id}"
    puts "HAHAHA!: #{embed_url}"
    content_tag :iframe, '', src: embed_url
  end

  def instagram_reel_embed(url)
    embed_body = content_tag :blockquote, class: 'instagram-media', 'data-instgrm-permalink': url do
      content_tag(:a, '', href: url)
    end
    embed_body + content_tag(:script, '', src: 'https://www.instagram.com/embed.js', charset: 'utf-8', async: true)
  end

  def instagram_embed(url)
    embed_body = content_tag :blockquote, class: 'instagram-media', 'data-instgrm-permalink': url do
      content_tag(:a, '', href: url)
    end
    embed_body + content_tag(:script, '', src: 'https://www.instagram.com/embed.js', charset: 'utf-8', async: true)
  end

  def twitter_embed(url)
    embed_body = content_tag :blockquote, class: 'twitter-tweet' do
      content_tag(:a, '', href: url)
    end
    embed_body + content_tag(:script, '', src: 'https://platform.twitter.com/widgets.js', charset: 'utf-8', async: true)
  end

  def removing_wordpress_tags(body)
    body.gsub(/\[caption.*?\](.*?)\[\/caption\]/, '\1')
  end

  def debug_id(article)
    return unless Rails.env.development? && article.imported_id.present?

    content_tag :span, "ID: #{article.imported_id}", style: 'margin-left: .5rem;'
  end
end

app/views/articles/_editor.html.erb
<% url = article.persisted? ? article_path(article) : articles_path %>
<%= form_with model: article, url: url, local: true do |form| %>
  <%= tag.div(flash[:alert], class: "flash flash--alert") if flash[:alert] %>
  <%= tag.div(flash[:notice], class: "flash flash--notice") if flash[:notice] %>

  <%= form.select :book_id, options_for_select(books.map { |book| [book.title, book.id] }, article.book_id), required: true %>
  <%= form.text_field :title, required: true, autofocus: true, placeholder: "Enter title", value: article.title %>
  <%= form.text_area :body, required: true, placeholder: "Enter content", value: article.body %>
  <%= form.select :status, options_for_select(Article::OFFICIAL_STATUSES.map { |status| [status, status] }, (article.status || 'publish')), include_blank: false %>
  <%= form.text_field :published_at, required: true, placeholder: "Enter published_at", value: (article.published_at || Time.current).strftime("%Y-%m-%d %H:%M:%S") %>
  <%= form.submit "Save" %>
<% end %>

app/views/articles/edit.html.erb
<div id="book-title-wrapper">
  <%= link_to book_path(@article.book) do %>
    <div id="book-title">
      <h1><%= @article.book.title %></h1>
      <h2><%= @article.book.description %></h2>
    </div>
  <% end %>
</div>

<div class="article-editor simple-form">
  <%= render "editor", article: @article, books: @books %>
</div>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/articles/new.html.erb
<div id="book-title-wrapper">
  <%= link_to book_path(@article.book) do %>
    <div id="book-title">
      <h1><%= @article.book.title %></h1>
      <h2><%= @article.book.description %></h2>
    </div>
  <% end %>
</div>

<div class="article-editor simple-form">
<%= render "editor", article: @article, books: @books %>
</div>

app/views/articles/show.html.erb
<div id="book-title-wrapper">
  <%= link_to book_path(@book) do %>
    <div id="book-title">
      <h1><%= @book.title %></h1>
      <h2><%= @book.description %></h2>
    </div>
  <% end %>
</div>

<%= tag.div class: "article article--#{@article.book.theme_slug}" do %>
  <div class="article__content">
    <h1 class="article__content__title"><%= @article.title %></h1>
    <div class="article__content__body">
      <%= body_with_pre_wrap(@article) %>
    </div>
  </div>
  <p class="article__meta">
    <%= date_only(@article.published_at) || @article.status %>
    <% if author?(@article) %>
      <span>（<%= artcile_char_counts(@article) %>文字）</span>
    <% end %>
    <%= debug_id(@article) %>
  </p>
  <div class="article__action-buttons">
    <div>
      <% if @article.prev_article.present? %>
        <%= link_to "前へ", article_path(@article.prev_article) %>
      <% end %>
    </div>
    <div>
      <%= link_to "一覧", book_path(@article.book) %>
    </div>
    <div>
      <% if @article.next_article.present? %>
        <%= link_to "後へ", article_path(@article.next_article) %>
      <% end %>
    </div>
  </div>
  <% if author?(@article) %>
    <div class="article__action-buttons">
      <div>
        <%= link_to "編集", edit_article_path(@article) %>
      </div>
      <div>
        <% if @article.status != 'deleted' %>
          <%= link_to "削除", article_path(@article), data: {turbo_method: :delete, turbo_confirm: "後悔しませんね？"} %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>