config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"

  # [Passing from Old WordPress URLs]
  get "archives/:book_slug/:id" => "wordpress_passers#show", as: :wordpress_passer

  # [User Auths (Default)]
  resource :session, except: [:show]
  resources :passwords, param: :token

  # [User Features]
  resources :users, only: [:new, :create, :show]

  # [Book Features]
  resources :books, param: :slug do
    get ':year', to: 'books#show', on: :member, as: :show_with_year, constraints: { year: /\d{4}/ }
    get ':year/:month', to: 'books#show', on: :member, as: :show_with_year_and_month, constraints: { year: /\d{4}/, month: /\d{1,2}/ }

    get 'rss', to: 'books#rss', on: :member

    resources :random_articles, only: [:index]
  end

  # [Article Features]
  resources :articles

  # [Random Article Feature]
  resources :random_articles, only: [:index]

  # [API Features]
  namespace :api do
    namespace :v1 do
      resources :articles, only: [:index, :show]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :books, foreign_key: :author_user_id

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]

  def new
    @user = User.new
  end

  def create
    user = User.create!(user_params)

    redirect_to new_session_path
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:display_name, :email_address, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1 class='diarin-title'>
  <%= link_to root_path do %>
    Diarin
  <% end %>
</h1>

<div class="simple-form">
  <%= form_with model: @user, url: users_path do |form| %>
    <%= tag.div(flash[:alert], class: "flash flash--alert") if flash[:alert] %>
    <%= tag.div(flash[:notice], class: "flash flash--notice") if flash[:notice] %>

    <%= form.text_field :display_name, required: true, autofocus: true, autocomplete: "name", placeholder: "Enter display name", value: params[:display_name] %>
    <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "username", placeholder: "Enter your email address", value: params[:email_address] %>
    <%= form.password_field :password, required: true, autocomplete: "current-password", placeholder: "Enter your password", maxlength: 72 %>
    <%= form.submit "Register" %>
    <%= link_to "Already have an account?", new_session_path %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1 class='diarin-title'>
  <%= link_to root_path do %>
    Diarin
  <% end %>
</h1>

<div class="user-menu">
  <div class="user-info">
    <h2>User Information</h2>
    <dl>
      <dt>Display Name</dt>
      <dd><%= @user.display_name %></dd>
      <dt>Email Address</dt>
      <dd><%= @user.email_address %></dd>
      <dt>Password</dt>
      <dd>********</dd>
    </dl>
  </div>

  <div class="writing-books">
    <h2>Books</h2>
      <dl>
        <% @user.books.each do |book| %>
          <dt><%= book.title %></dt>
          <dd><%= link_to 'Show', book %></dd>
        <% end %>
        <dt>New one?</dt>
        <dd><%= link_to 'Create', new_book_path %></dd>
      </dl>
  </div>
  <%= button_to 'Sign Out', session_path, method: :delete %>
</div>