config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"

  # [Passing from Old WordPress URLs]
  get "archives/:book_slug/:id" => "wordpress_passers#show", as: :wordpress_passer

  # [User Auths (Default)]
  resource :session, except: [:show]
  resources :passwords, param: :token

  # [User Features]
  resources :users, only: [:new, :create, :show]

  # [Book Features]
  resources :books, param: :slug do
    get ':year', to: 'books#show', on: :member, as: :show_with_year, constraints: { year: /\d{4}/ }
    get ':year/:month', to: 'books#show', on: :member, as: :show_with_year_and_month, constraints: { year: /\d{4}/, month: /\d{1,2}/ }

    get 'rss', to: 'books#rss', on: :member

    resources :random_articles, only: [:index]
  end

  # [Article Features]
  resources :articles

  # [Random Article Feature]
  resources :random_articles, only: [:index]

  # [API Features]
  namespace :api do
    namespace :v1 do
      resources :articles, only: [:index, :show]
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_user_id
  has_many :articles, dependent: :destroy

  scope :published, -> { where('published_at < ?', Time.zone.now) }

  FIRST_VIEW_TYPES = %w[list latest_article].freeze
  COLORS = %w[auto red green blue yellow pink purple].freeze

  def to_param
    slug
  end

  def year_months
    @year_months ||= {}
    articles.published
            .group("strftime('%Y-%m', datetime(published_at, '+9 hours'))")
            .order("published_at DESC")
            .select("strftime('%Y%m', datetime(published_at, '+9 hours')) as year_month, count(*) as count")
            .map do |article|
      year_month_int = article.year_month.to_i
      year = year_month_int / 100
      month = year_month_int % 100
      {
        year: year,
        month: month,
        count: article.count
      }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  allow_unauthenticated_access only: [:index, :show, :rss]

  def index
    @books = Book.published
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.author = Current.user
    if @book.save
      redirect_to book_path(@book.slug)
    else
      flash.now[:alert] = @book.errors.full_messages.join("\n")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @book = Book.find_by(slug: params[:slug])
    redirect_to books_path if @book.blank?

    handle_wordpress_url if wordpress_id_param.present?

    @articles = @book.articles.published.order(published_at: :desc).limit(100)

    year = params[:year].to_i if params[:year].present?
    month = params[:month].to_i if params[:month].present?
    @articles = filter_by_year_month(@articles, year, month)

    search_param = params[:search]
    @articles = filter_by_seach_params(@articles, search_param)

    @is_first_view = first_view?
  end

  def edit
    @book = Book.find_by(slug: params[:slug])
  end

  def update
    @book = Book.find_by(slug: params[:slug])
    if @book.update(book_params)
      redirect_to book_path(@book.slug)
    else
      render :edit
    end
  end

  def rss
    @book = Book.find_by(slug: params[:slug])
    # not found instead of redirecting
    head :not_found and return if @book.blank?
    @articles = @book.articles.published.order(published_at: :desc).limit(20)

    respond_to do |format|
      format.rss { render layout: false }
      format.xml { render layout: false }
    end
  end

  private
    def first_view?
      (params.keys - %w[controller action slug]).empty?
    end

    def filter_by_year_month(articles, year, month)
      if year.present? && month.present?
        articles.with_year_month(year, month)
      elsif year.present?
        articles.with_year(year)
      else
        articles
      end
    end

    def filter_by_seach_params(articles, search_param)
      search_keys = search_param.to_s.split(/\s+/)
      search_keys.each do |key|
        articles = articles.search(key)
      end
      articles
    end

    def book_params
      params.require(:book).permit(
        :title,
        :description,
        :slug,
        :theme_slug,
        :first_view_type,
        :color,
        :published_at)
    end

    def wordpress_id_param
      params[:p]
    end

    def handle_wordpress_url
      article = Article.find_by(imported_id: wordpress_id_param, book: @book)

      return if article.blank?
      redirect_to article_path(article)
    end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_updated_label(book)
    book_updated_at = book.articles.published.order(published_at: :desc).first&.published_at

    return '' if book_updated_at.nil?

    return "#{date_only(book_updated_at)} 更新"

  end
end

app/views/books/_article.html.erb
<% cache article do %>
  <div class='article-list__item'>
    <%= link_to article_path(article), class: 'article-list__item__link' do %>
      <div class='article-list__item__line'>
        <div class='article-list__item__title'>
          <%= article.title %>
        </div>
        <div class='article-list__item__published-at'>
          <%= date_only(article.published_at) %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/_book-form.html.erb
<% is_new = book.new_record? %>
<% method = is_new ? :post : :patch %>
<% url = is_new ? books_path : book_path(book) %>

<div class="simple-form">
  <%= form_with model: book, url: url, method: method do |form| %>
    <%= tag.div(flash[:alert], class: "flash flash--alert") if flash[:alert] %>
    <%= tag.div(flash[:notice], class: "flash flash--notice") if flash[:notice] %>

    <% if is_new %>
      <%= form.text_field :slug, requiresd: true, autofocus: true, placeholder: "Enter slug", value: book.slug %>
    <% end %>
    <%= form.text_field :title, requiresd: true, autofocus: true, placeholder: "Enter title", value: book.title %>
    <%= form.text_field :description, required: true, autofocus: true, placeholder: "Enter description", value: book.description %>
    <%= form.select :theme_slug, options_for_select(Theme::SLUGS, book.theme_slug), required: true %>
    <%= form.select :first_view_type, options_for_select(Book::FIRST_VIEW_TYPES, book.first_view_type), required: true %>
    <%= form.select :color, options_for_select(Book::COLORS, book.color), required: true %>
    <%= form.text_field :published_at, required: true, placeholder: "Enter published_at", value: (book.published_at || Time.current).strftime("%Y-%m-%d %H:%M:%S") %>
    <%= form.submit "Save" %>
  <% end %>
</div>

app/views/books/_book.html.erb
<% book_updated_label = book_updated_label(book) %>
<% cache "#{book.updated_at}-#{book_updated_label}" do %>
  <%= tag.div class: ['book-list__item'] do %>
    <%= link_to book_path(book), class: 'book-list__item__link' do %>
      <figure class="book">
        <h2><%= book.title %></h2>
        <div class="book__label">
          <p class='book__label__description'><%= book.description %></p>
          <p class='book__label__update'><%= book_updated_label %></p>
        </div>
      </figure>
    <% end %>
  <% end %>
<% end %>

app/views/books/_first-view-article.html.erb
<% cache [article, author?(article)] do %>
  <%= tag.div class: "article article--#{article.book.theme_slug}" do %>
    <div class="article__content">
      <h1 class="article__content__title">
        <%= link_to article_path(article) do %>
        <%= article.title %>
      <% end %>
      </h1>
      <div class="article__content__body">
        <%= body_with_pre_wrap(article) %>
      </div>
    </div>
    <p class="article__meta">
      <%= date_only(article.published_at) || article.status %>
      <% if author?(article) %>
        <span>（<%= artcile_char_counts(article) %>文字）</span>
      <% end %>
      <%= debug_id(article) %>
    </p>
    <div class="article__action-buttons">
      <div>
        <% if article.prev_article.present? %>
          <%= link_to "前へ", article_path(article.prev_article) %>
        <% end %>
      </div>
      <div>
        <% if article.next_article.present? %>
          <%= link_to "後へ", article_path(article.next_article) %>
        <% end %>
      </div>
    </div>
    <% if author?(article) %>
      <div class="article__action-buttons">
        <div>
          <%= link_to "編集", edit_article_path(article) %>
        </div>
        <div>
          <% if article.status != 'deleted' %>
            <%= link_to "削除", article_path(article), data: {turbo_method: :delete, turbo_confirm: "後悔しませんね？"} %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/books/edit.html.erb
<div id="book-title-wrapper">
  <%= link_to book_path(@book) do %>
    <div id="book-title">
      <h1><%= @book.title %></h1>
      <h2><%= @book.description %></h2>
    </div>
  <% end %>
</div>

<%= render 'book-form', book: @book %>

app/views/books/index.html.erb
<h1>Diarin</h1>
<div class="book-list">
  <%= render @books %>
</div>

app/views/books/new.html.erb
<h1 class='diarin-title'>
  <%= link_to root_path do %>
    Diarin
  <% end %>
</h1>

<%= render 'book-form', book: @book %>

app/views/books/show.html.erb
<div id="diain-logo">
  <%= link_to books_path do %>
    produced by
    <span class="diarin-name">Diarin</span>
  <% end %>
</div>
<div id="book-title-wrapper">
  <%= link_to book_path(@book) do %>
    <div id="book-title">
      <h1><%= @book.title %></h1>
      <h2><%= @book.description %></h2>
    </div>
  <% end %>
</div>

<div class="book-first-view">
  <div class="main-contents">
    <% if @book.first_view_type == 'latest_article'&& @articles.present? && @is_first_view %>
      <div class="book-first-view__item article">
        <%= render partial: 'books/first-view-article', locals: { article: @articles.first } %>
      </div>
    <% end %>
    <%= tag.div class: "book-first-view__item article-list article-list--#{@book.theme_slug}" do %>
      <% if @articles.blank? %>
        はっはっは。見つかりませんでしたよ。
      <% else %>
        <%= render partial: 'books/article', collection: @articles, as: :article %>
      <% end %>
    <% end %>
  </div>
  <div class="sidebar-contents">
    <% if author?(@book) %>
      <div class="manage-field actions-field book-first-view__item">
        <%= link_to new_article_path(book_slug: @book.slug) do %>
          <button class="actions-field__button">+ Write New</button>
        <% end %>
        <%= link_to edit_book_path(@book.slug) do %>
          <button class="actions-field__button">Book Config</button>
        <% end %>
      </div>
    <% end %>
    <div class="search-field book-first-view__item">
      <%= form_with url: book_path(@book.slug), method: :get, html: { class: "search-field__form" } do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search articles", class: "search-field__input" %>
        <%= submit_tag "Search", class: "search-field__submit" %>
      <% end %>
    </div>
    <div class="year-month-list book-first-view__item">
      <% selected_year = params[:year].to_i %>
      <% selected_month = params[:month].to_i %>
      <% current_year = nil %>
      <% @book.year_months.each do |year_month| %>
        <% if current_year != year_month[:year] %>
          <% current_year = year_month[:year] %>
          <% year_span_class = ['year-month-list__title'] %>
          <% year_span_class << 'year-month-list__title--selected' if selected_year == current_year %>
          <%= content_tag :span, class: year_span_class.join(' ') do %>
            <% link_to show_with_year_book_path(@book.slug, year: current_year) do %>
              <%= current_year %>年
            <% end %>
          <% end %>
        <% end %>

        <% year_month_div_class = ['year-month-list__item'] %>
        <% year_month_div_class << 'year-month-list__item--selected' if selected_year == current_year && selected_month == year_month[:month] %>
        <%= content_tag :div, class: year_month_div_class.join(' ') do %>
          <%= link_to show_with_year_and_month_book_path(@book.slug, year: year_month[:year], month: year_month[:month]) do %>
            <%= year_month[:year] %>年<%= year_month[:month] %>月（<%= year_month[:count] %>）
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="subscribing-field actions-field actions-field--single-action book-first-view__item">
      <%= link_to rss_book_path(@book, format: :rss) do %>
        <button class="actions-field__button">+ RSS Feed</button>
      <% end %>
    </div>
  </div>
</div>